{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "target up status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    { "expr": "up\r\n\r\n\r\n", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "pod-cpu-usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", pod!=\"\"}[2m])) by (pod)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod-restart-count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}